;;;  -*- Package: thrift-generated -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(def-package :thrift-generated)

(thrift:def-struct "foo"
  (("bar" nil :type i32 :id 1)
   ("baz" nil :type i32 :id 2)
   ("qux" nil :type i32 :id 3)
   ("bop" nil :type i32 :id 4)))

