;;;  -*- Package: thrift-generated -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(in-package :thrift-generated)

(thrift:def-constant "myInt" 3)

(thrift:def-constant "GEN_ENUM_NAMES" (thrift:map 
  (cl:cons   1 "HOWDY")
  (cl:cons   2 "PARTNER")))

(thrift:def-constant "hex_const" 31)

(thrift:def-constant "GEN_ME" -3523553)

(thrift:def-constant "GEn_DUB" 325.532)

(thrift:def-constant "GEn_DU" 85.2355)

(thrift:def-constant "GEN_STRING" "asldkjasfd")

(thrift:def-constant "GEN_MAP" (thrift:map 
  (cl:cons 35532 233)
  (cl:cons 43523 853)))

(thrift:def-constant "GEN_LIST" (thrift:list
    235235
    23598352
    3253523
    ))

(thrift:def-constant "GEN_MAPMAP" (thrift:map 
  (cl:cons 235 (thrift:map 
    (cl:cons 532 53255)
    (cl:cons 235 235)  ))))

(thrift:def-constant "GEN_MAP2" (thrift:map 
  (cl:cons "hello" 233)
  (cl:cons "lkj98d" 853)
  (cl:cons "lkjsdf" 98325)))

(thrift:def-constant "GEN_THING" (make-instance 'thing 
  :hello 325
  :goodbye 325352
  ))

(thrift:def-constant "GEN_WHAT" (thrift:map 
  (cl:cons 35 (make-instance 'thing 
    :hello 325
    :goodbye 325352
    ))))

(thrift:def-constant "GEN_SET" (thrift:set
    235
    235
    53235
    ))

