;;;  -*- Package: thrift-generated -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(in-package :thrift-generated)

(thrift:def-constant "INT32CONSTANT" 9853)

(thrift:def-constant "INT16CONSTANT" 1616)

(thrift:def-constant "MAPCONSTANT" (thrift:map 
  (cl:cons "hello" "world")
  (cl:cons "goodnight" "moon")))

