;;;  -*- Package: thrift-generated -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(def-package :thrift-generated)

(thrift:def-struct "oldschool"
  (("im_int" nil :type i16 :id 1)
   ("im_str" nil :type string :id 2)
   ("im_big" nil :type (list (map i32 string)) :id 3)))

(thrift:def-struct "simple"
  (("im_default" nil :type i16 :id 1)
   ("im_required" nil :type i16 :id 2)
   ("im_optional" nil :type i16 :id 3)))

(thrift:def-struct "tricky1"
  (("im_default" nil :type i16 :id 1)))

(thrift:def-struct "tricky2"
  (("im_optional" nil :type i16 :id 1)))

(thrift:def-struct "tricky3"
  (("im_required" nil :type i16 :id 1)))

(thrift:def-struct "complex"
  (("cp_default" nil :type i16 :id 1)
   ("cp_required" nil :type i16 :id 2)
   ("cp_optional" nil :type i16 :id 3)
   ("the_map" nil :type (map i16 (struct "simple")) :id 4)
   ("req_simp" nil :type (struct "simple") :id 5)
   ("opt_simp" nil :type (struct "simple") :id 6)))

(thrift:def-struct "manyopt"
  (("opt1" nil :type i32 :id 1)
   ("opt2" nil :type i32 :id 2)
   ("opt3" nil :type i32 :id 3)
   ("def4" nil :type i32 :id 4)
   ("opt5" nil :type i32 :id 5)
   ("opt6" nil :type i32 :id 6)))

(thrift:def-struct "javatesthelper"
  (("req_int" nil :type i32 :id 1)
   ("opt_int" nil :type i32 :id 2)
   ("req_obj" nil :type string :id 3)
   ("opt_obj" nil :type string :id 4)
   ("req_bin" nil :type string :id 5)
   ("opt_bin" nil :type string :id 6)))

