;;;  -*- Package: thrift-generated -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(in-package :thrift-generated)

(thrift:def-constant "CMAP" (thrift:map 
  (cl:cons 235 (thrift:map 
    (cl:cons 235 235)  ))
  (cl:cons 53 (thrift:map 
    (cl:cons 53 53)  ))))

(thrift:def-constant "CINT" 325)

(thrift:def-constant "WHOA" (make-instance 'hello 
  :simple 532
  ))

