;;;  -*- Package: thrift-generated -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(def-package :thrift-generated)

(thrift:def-service "Service" nil
  (:method "echoVoid" (() void))
  (:method "echoByte" ((("arg" byte 1)) byte))
  (:method "echoI32" ((("arg" i32 1)) i32))
  (:method "echoI64" ((("arg" i64 1)) i64))
  (:method "echoString" ((("arg" string 1)) string))
  (:method "echoList" ((("arg" (list byte) 1)) (list byte)))
  (:method "echoSet" ((("arg" (set byte) 1)) (set byte)))
  (:method "echoMap" ((("arg" (map byte byte) 1)) (map byte byte))))
