;;;  -*- Package: thrift.test -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(def-package :thrift.test)


(defun test-void ())

(defun test-string (string-thing) string-thing)

(defun test-byte (byte-thing) byte-thing)

(defun test-i32 (i32-thing) i32-thing)
(defun test-i64 (i64-thing) i64-thing)

(defun test-double (double-thing) double-thing)
(defun test-struct (struct-thing) struct-thing)
(defun test-nest (struct-thing) struct-thing)
(defun test-map (map-thing) map-thing)
(defun test-set (set-132-thing) set-132-thing)
(defun test-list (list-132-thing) list-132-thing)
(defun test-enum (enum-numberz-thing) enum-numberz-thing)
(defun test-typedef (typedef-i64-thing) typedef-i64-thing)
(defun test-map-map (i32-thing) (map i32-thing (map (cons i32-thing i32-thing))))


(defun test-insanity (struct-insanity-thing) (map 1 (map (cons 1 struct-insanity-thing))))

(defun test-multi (arg0-byte arg1-i32 arg2-i64 arg3-map arg4-enum-numberz arg5-i64)
  (make-instance 'xtruct))

(defun test-exception (string-thing)
  (error 'xception))

(defun test-multi-exception (arg-string arg1-string struct-xtruct)
  (error 'xception))

(defun test-oneway (secondstosleep) nil)


(defun blah-blah () nil)

