;;;  -*- Package: cassandra -*-
;;;
;;; Autogenerated by Thrift
;;; DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

(in-package :cassandra)

(thrift:def-constant "VERSION" "8.1.0")

